DELIMITER //
DROP PROCEDURE IF EXISTS test1;
CREATE PROCEDURE test1()
 BEGIN
    SELECT 'hi';
 END //
DELIMITER ;

CALL test1();

DELIMITER //
DROP PROCEDURE IF EXISTS test2;
CREATE PROCEDURE test2(IN n VARCHAR(60))
 BEGIN
 
 IF(n = 'm') THEN
    SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT = "ahbh";
    END IF;
    
    SELECT n;
	SELECT "hi";
 END //
DELIMITER ;

CALL test2('g');

SELECT @n;

DELIMITER //
DROP PROCEDURE IF EXISTS test3;
CREATE PROCEDURE test3(in m VARCHAR(60), OUT n VARCHAR(60), OUT o VARCHAR(60))
 BEGIN
 
 SET n := m;
 SET o := m;
 END //
DELIMITER ;

CALL test3('AA', @n, @o);

DELIMITER //
DROP PROCEDURE IF EXISTS test4;
CREATE PROCEDURE test4(in m VARCHAR(60))
 BEGIN
 
 SELECT m;
 SELECT 'ppp';
 END //
DELIMITER ;

SELECT * FROM user WHERE name = 'Alex Name' or name = 'a';
CALL test4('AA');