DELIMITER //
DROP PROCEDURE IF EXISTS test1;
CREATE PROCEDURE test1()
 BEGIN
    SELECT 'hi';
 END //
DELIMITER ;

CALL test1();

DELIMITER //
DROP PROCEDURE IF EXISTS test2;
CREATE PROCEDURE test2(IN n VARCHAR(60))
 BEGIN
 
 IF(n = 'm') THEN
    SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT = "ahbh";
    END IF;
    
    SELECT n;
	SELECT "hi";
 END //
DELIMITER ;

CALL test2('g');

DELIMITER //
DROP PROCEDURE IF EXISTS test3;
CREATE PROCEDURE test3(IN n VARCHAR(60))
 BEGIN
 
 SELECT n;
 SELECT "hi";
 END //
DELIMITER ;